-- =====================================================================
-- Project KEYSTONE — V1 initial schema
-- Field Service Management Platform (Meridian Facilities Management)
--
-- Flyway is the SOLE owner of the schema (spring.jpa.hibernate.ddl-auto=none).
-- Every column here maps 1:1 to a JPA field in com.meridian.keystone.domain.
--
-- Conventions:
--   * Primary keys: BIGINT GENERATED BY DEFAULT AS IDENTITY.
--     "BY DEFAULT" (not "ALWAYS") so the V2 seed can insert explicit ids;
--     we reset the identity sequences at the end of V2 so app inserts continue
--     cleanly from MAX(id)+1.
--   * Money: NUMERIC(12,2).
--   * Enums: stored as VARCHAR(20) (Hibernate @Enumerated(STRING)); a CHECK
--     constraint pins the allowed values at the database level.
--   * Timestamps: TIMESTAMPTZ (maps to java.time.Instant, stored in UTC).
--   * Audit columns (created_at / updated_at / version) are populated by JPA
--     auditing + optimistic locking on the mutable entities.
-- =====================================================================

-- ---------------------------------------------------------------------
-- customers  (Customer extends BaseEntity)
-- ---------------------------------------------------------------------
CREATE TABLE customers (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

-- ---------------------------------------------------------------------
-- sites  (Site extends BaseEntity) — Customer 1—* Site
-- ---------------------------------------------------------------------
CREATE TABLE sites (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT       NOT NULL,
    name        VARCHAR(150) NOT NULL,
    address     VARCHAR(300),
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_sites_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_sites_customer_id ON sites (customer_id);

-- ---------------------------------------------------------------------
-- users  (User extends BaseEntity)
-- customer_id is nullable — only set for CUSTOMER-role users (data scoping).
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    customer_id   BIGINT,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_users_role
        CHECK (role IN ('DISPATCHER', 'TECHNICIAN', 'MANAGER', 'CUSTOMER'))
);

CREATE INDEX idx_users_customer_id ON users (customer_id);
CREATE INDEX idx_users_role        ON users (role);

-- ---------------------------------------------------------------------
-- parts  (Part extends BaseEntity)
-- Stock must never go negative — enforced here AND in the service layer.
-- ---------------------------------------------------------------------
CREATE TABLE parts (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(50)   NOT NULL,
    name           VARCHAR(150)  NOT NULL,
    unit_cost      NUMERIC(12,2) NOT NULL DEFAULT 0,
    stock_quantity INTEGER       NOT NULL DEFAULT 0,
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uq_parts_sku UNIQUE (sku),
    CONSTRAINT ck_parts_stock_nonneg   CHECK (stock_quantity >= 0),
    CONSTRAINT ck_parts_unit_cost_nonneg CHECK (unit_cost >= 0)
);

-- ---------------------------------------------------------------------
-- work_orders  (WorkOrder extends BaseEntity) — the heart of the system
-- Always has a customer and a site; optionally an assignee (technician).
-- ---------------------------------------------------------------------
CREATE TABLE work_orders (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(30)   NOT NULL,
    title               VARCHAR(200)  NOT NULL,
    description         VARCHAR(4000),
    priority            VARCHAR(20)   NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'NEW',
    customer_id         BIGINT        NOT NULL,
    site_id             BIGINT        NOT NULL,
    assignee_id         BIGINT,
    sla_due_at          TIMESTAMPTZ,
    sla_status          VARCHAR(20)   NOT NULL DEFAULT 'ON_TRACK',
    total_labor_minutes INTEGER       NOT NULL DEFAULT 0,
    total_parts_cost    NUMERIC(12,2) NOT NULL DEFAULT 0,
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL,
    updated_at          TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uq_work_orders_code UNIQUE (code),
    CONSTRAINT fk_work_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_work_orders_site
        FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_work_orders_assignee
        FOREIGN KEY (assignee_id) REFERENCES users (id),
    CONSTRAINT ck_work_orders_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT ck_work_orders_status
        CHECK (status IN ('NEW', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD',
                          'COMPLETED', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_work_orders_sla_status
        CHECK (sla_status IN ('ON_TRACK', 'AT_RISK', 'BREACHED')),
    CONSTRAINT ck_work_orders_labor_nonneg CHECK (total_labor_minutes >= 0),
    CONSTRAINT ck_work_orders_parts_cost_nonneg CHECK (total_parts_cost >= 0)
);

CREATE INDEX idx_work_orders_customer_id ON work_orders (customer_id);
CREATE INDEX idx_work_orders_site_id     ON work_orders (site_id);
CREATE INDEX idx_work_orders_assignee_id ON work_orders (assignee_id);
CREATE INDEX idx_work_orders_status      ON work_orders (status);
CREATE INDEX idx_work_orders_sla_due_at  ON work_orders (sla_due_at);

-- ---------------------------------------------------------------------
-- work_order_status_history  (append-only audit trail)
-- One row per status change: from, to, who, when, optional note.
-- No version / updated_at — rows are never edited or deleted.
-- from_status is NULL for the initial row written at creation.
-- ---------------------------------------------------------------------
CREATE TABLE work_order_status_history (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT       NOT NULL,
    from_status   VARCHAR(20),
    to_status     VARCHAR(20)  NOT NULL,
    changed_by_id BIGINT,
    note          VARCHAR(1000),
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_wosh_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id),
    CONSTRAINT fk_wosh_changed_by
        FOREIGN KEY (changed_by_id) REFERENCES users (id),
    CONSTRAINT ck_wosh_from_status
        CHECK (from_status IS NULL OR from_status IN
              ('NEW', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD',
               'COMPLETED', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_wosh_to_status
        CHECK (to_status IN
              ('NEW', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD',
               'COMPLETED', 'CLOSED', 'CANCELLED'))
);

CREATE INDEX idx_wosh_work_order_id ON work_order_status_history (work_order_id);

-- ---------------------------------------------------------------------
-- part_usage  (PartUsage) — parts consumed on a work order
-- Logging usage decrements Part.stock in the same transaction (M3).
-- unit_cost_at_use snapshots the cost so historical totals stay stable.
-- ---------------------------------------------------------------------
CREATE TABLE part_usage (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id    BIGINT        NOT NULL,
    part_id          BIGINT        NOT NULL,
    quantity         INTEGER       NOT NULL,
    unit_cost_at_use NUMERIC(12,2) NOT NULL,
    logged_by_id     BIGINT,
    created_at       TIMESTAMPTZ   NOT NULL,
    CONSTRAINT fk_part_usage_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id),
    CONSTRAINT fk_part_usage_part
        FOREIGN KEY (part_id) REFERENCES parts (id),
    CONSTRAINT fk_part_usage_logged_by
        FOREIGN KEY (logged_by_id) REFERENCES users (id),
    CONSTRAINT ck_part_usage_quantity_pos CHECK (quantity > 0),
    CONSTRAINT ck_part_usage_cost_nonneg  CHECK (unit_cost_at_use >= 0)
);

CREATE INDEX idx_part_usage_work_order_id ON part_usage (work_order_id);
CREATE INDEX idx_part_usage_part_id       ON part_usage (part_id);

-- ---------------------------------------------------------------------
-- time_logs  (TimeLog) — labour logged by a technician, in minutes
-- ---------------------------------------------------------------------
CREATE TABLE time_logs (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT       NOT NULL,
    technician_id BIGINT       NOT NULL,
    minutes       INTEGER      NOT NULL,
    note          VARCHAR(1000),
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_time_logs_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id),
    CONSTRAINT fk_time_logs_technician
        FOREIGN KEY (technician_id) REFERENCES users (id),
    CONSTRAINT ck_time_logs_minutes_pos CHECK (minutes > 0)
);

CREATE INDEX idx_time_logs_work_order_id ON time_logs (work_order_id);
CREATE INDEX idx_time_logs_technician_id ON time_logs (technician_id);
