-- =====================================================================
-- Project KEYSTONE — V2 seed data
--
-- A reviewer must be able to clone, run migrations, and immediately log in.
-- All seed users share the password:  ChangeMe123!
-- (BCrypt $2a$10$ hashes below were generated and round-trip verified.)
--
-- Explicit ids are inserted here (columns are GENERATED BY DEFAULT AS
-- IDENTITY). The identity sequences are reset at the END of this file so
-- the application's own inserts continue from MAX(id)+1 without collisions.
--
-- The data is internally consistent: the seeded part usage below decrements
-- the referenced part's stock, and each work order's totals reflect its
-- seeded time logs and part usage.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Customers (2)
-- ---------------------------------------------------------------------
INSERT INTO customers (id, name, contact_email, contact_phone, version, created_at, updated_at) VALUES
    (1, 'Acme Corporation',  'ops@acme.dev',         '+1-202-555-0111', 0, now(), now()),
    (2, 'Globex Industries', 'facilities@globex.dev','+1-202-555-0122', 0, now(), now());

-- ---------------------------------------------------------------------
-- Sites (4) — two per customer
-- ---------------------------------------------------------------------
INSERT INTO sites (id, customer_id, name, address, version, created_at, updated_at) VALUES
    (1, 1, 'Acme HQ Tower',     '100 Market St, Springfield',      0, now(), now()),
    (2, 1, 'Acme Warehouse',    '450 Industrial Ave, Springfield', 0, now(), now()),
    (3, 2, 'Globex Plaza',      '77 Innovation Dr, Ogdenville',    0, now(), now()),
    (4, 2, 'Globex Data Center','9 Cooling Loop Rd, Ogdenville',   0, now(), now());

-- ---------------------------------------------------------------------
-- Users (one per role, plus a second technician)
-- Password for every user below: ChangeMe123!
--   1 manager@meridian.dev     MANAGER
--   2 dispatcher@meridian.dev  DISPATCHER
--   3 tech1@meridian.dev       TECHNICIAN
--   4 tech2@meridian.dev       TECHNICIAN
--   5 alice@acme.dev           CUSTOMER  (linked to Acme, customer_id = 1)
-- ---------------------------------------------------------------------
INSERT INTO users (id, email, password_hash, full_name, role, customer_id, active, version, created_at, updated_at) VALUES
    (1, 'manager@meridian.dev',    '$2a$10$TMeuCucxBQd/WLYDnD/CWe.0xt1R7RADGMdBx3ATA1WOM4wEgATrK', 'Morgan Manager',    'MANAGER',    NULL, TRUE, 0, now(), now()),
    (2, 'dispatcher@meridian.dev', '$2a$10$TMeuCucxBQd/WLYDnD/CWe.0xt1R7RADGMdBx3ATA1WOM4wEgATrK', 'Dana Dispatcher',   'DISPATCHER', NULL, TRUE, 0, now(), now()),
    (3, 'tech1@meridian.dev',      '$2a$10$TMeuCucxBQd/WLYDnD/CWe.0xt1R7RADGMdBx3ATA1WOM4wEgATrK', 'Tomas Technician',  'TECHNICIAN', NULL, TRUE, 0, now(), now()),
    (4, 'tech2@meridian.dev',      '$2a$10$TMeuCucxBQd/WLYDnD/CWe.0xt1R7RADGMdBx3ATA1WOM4wEgATrK', 'Tara Technician',   'TECHNICIAN', NULL, TRUE, 0, now(), now()),
    (5, 'alice@acme.dev',          '$2a$10$TMeuCucxBQd/WLYDnD/CWe.0xt1R7RADGMdBx3ATA1WOM4wEgATrK', 'Alice Acme',        'CUSTOMER',   1,    TRUE, 0, now(), now());

-- ---------------------------------------------------------------------
-- Parts (6). NOTE: part id=6 stock is 78, not 80, because work order
-- WO-2026-0003 below consumes 2 units (see part_usage).
-- ---------------------------------------------------------------------
INSERT INTO parts (id, sku, name, unit_cost, stock_quantity, version, created_at, updated_at) VALUES
    (1, 'HVAC-FILT-20X25', 'HVAC Air Filter 20x25',    12.50, 120, 0, now(), now()),
    (2, 'CAP-45MFD',       'Capacitor 45 MFD',         18.00,  40, 0, now(), now()),
    (3, 'CONT-24V',        'Contactor 24V',            32.75,  25, 0, now(), now()),
    (4, 'THERM-PROG',      'Programmable Thermostat',  89.99,  15, 0, now(), now()),
    (5, 'BREAKER-20A',     'Circuit Breaker 20A',       9.25, 200, 0, now(), now()),
    (6, 'PVC-PIPE-1IN',    'PVC Pipe 1in (10ft)',       6.40,  78, 0, now(), now());

-- ---------------------------------------------------------------------
-- Work orders (3 samples spanning the lifecycle)
--   WO-2026-0001  ASSIGNED     (Acme HQ, HVAC, assigned to tech1)
--   WO-2026-0002  NEW          (Globex Plaza, electrical, unassigned)
--   WO-2026-0003  IN_PROGRESS  (Acme Warehouse, plumbing, tech2)
--                              totals reflect the time log + part usage below
-- ---------------------------------------------------------------------
INSERT INTO work_orders (id, code, title, description, priority, status, customer_id, site_id, assignee_id, sla_due_at, sla_status, total_labor_minutes, total_parts_cost, version, created_at, updated_at) VALUES
    (1, 'WO-2026-0001', 'Rooftop HVAC not cooling',
        'Tenant reports warm air on the top floor. Inspect rooftop unit and compressor.',
        'HIGH',   'ASSIGNED',    1, 1, 3, now() + INTERVAL '8 hours',  'ON_TRACK',  0,     0.00, 0, now() - INTERVAL '2 hours', now() - INTERVAL '1 hours'),
    (2, 'WO-2026-0002', 'Flickering lights in lobby',
        'Intermittent flickering across the main lobby fixtures. Check panel and breakers.',
        'MEDIUM', 'NEW',         2, 3, NULL, now() + INTERVAL '24 hours', 'ON_TRACK', 0,     0.00, 0, now() - INTERVAL '30 minutes', now() - INTERVAL '30 minutes'),
    (3, 'WO-2026-0003', 'Leaking pipe in restroom',
        'Active leak under the second-floor restroom sink. Shut off and replace section.',
        'URGENT', 'IN_PROGRESS', 1, 2, 4, now() + INTERVAL '4 hours',  'ON_TRACK', 90,    12.80, 0, now() - INTERVAL '3 hours', now() - INTERVAL '20 minutes');

-- ---------------------------------------------------------------------
-- Status history (append-only). from_status = NULL on the creation row.
-- Timestamps are staggered so the trail reads chronologically.
-- ---------------------------------------------------------------------
INSERT INTO work_order_status_history (id, work_order_id, from_status, to_status, changed_by_id, note, created_at) VALUES
    -- WO-2026-0001: created, then assigned
    (1, 1, NULL,          'NEW',         2, 'Work order created.',                  now() - INTERVAL '2 hours'),
    (2, 1, 'NEW',         'ASSIGNED',    2, 'Assigned to Tomas Technician.',        now() - INTERVAL '1 hours'),
    -- WO-2026-0002: created only
    (3, 2, NULL,          'NEW',         2, 'Work order created.',                  now() - INTERVAL '30 minutes'),
    -- WO-2026-0003: created, assigned, then started
    (4, 3, NULL,          'NEW',         2, 'Work order created.',                  now() - INTERVAL '3 hours'),
    (5, 3, 'NEW',         'ASSIGNED',    2, 'Assigned to Tara Technician (urgent).',now() - INTERVAL '2 hours 30 minutes'),
    (6, 3, 'ASSIGNED',    'IN_PROGRESS', 4, 'On site; water shut off, diagnosing.', now() - INTERVAL '2 hours');

-- ---------------------------------------------------------------------
-- Part usage on WO-2026-0003 (drives total_parts_cost = 2 x 6.40 = 12.80
-- and the reduced stock of part id=6 above).
-- ---------------------------------------------------------------------
INSERT INTO part_usage (id, work_order_id, part_id, quantity, unit_cost_at_use, logged_by_id, created_at) VALUES
    (1, 3, 6, 2, 6.40, 4, now() - INTERVAL '90 minutes');

-- ---------------------------------------------------------------------
-- Time log on WO-2026-0003 (drives total_labor_minutes = 90).
-- ---------------------------------------------------------------------
INSERT INTO time_logs (id, work_order_id, technician_id, minutes, note, created_at) VALUES
    (1, 3, 4, 90, 'Initial diagnosis, shutoff, and prep for pipe replacement.', now() - INTERVAL '80 minutes');

-- ---------------------------------------------------------------------
-- Reset identity sequences so application inserts continue from MAX(id)+1.
-- pg_get_serial_sequence resolves the sequence behind an IDENTITY column.
-- ---------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('customers',                'id'), (SELECT MAX(id) FROM customers));
SELECT setval(pg_get_serial_sequence('sites',                    'id'), (SELECT MAX(id) FROM sites));
SELECT setval(pg_get_serial_sequence('users',                    'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('parts',                    'id'), (SELECT MAX(id) FROM parts));
SELECT setval(pg_get_serial_sequence('work_orders',              'id'), (SELECT MAX(id) FROM work_orders));
SELECT setval(pg_get_serial_sequence('work_order_status_history','id'), (SELECT MAX(id) FROM work_order_status_history));
SELECT setval(pg_get_serial_sequence('part_usage',               'id'), (SELECT MAX(id) FROM part_usage));
SELECT setval(pg_get_serial_sequence('time_logs',                'id'), (SELECT MAX(id) FROM time_logs));
