-- ============================================================================
-- V3 — Milestone 3 additions: SLA completion tracking, race-free work-order
--      codes, and in-app notifications.
--
--   * work_orders.completed_at  — when the job was completed. Lets the SLA
--     freeze at its final outcome (met vs breached) instead of drifting, and
--     powers "average completion time" on the dashboard.
--   * work_order_code_seq       — generates WO-<year>-<nnnn> codes without a
--     read-modify-write race. Starts at 4 because V2 seeded 0001..0003.
--   * notifications             — SLA breach / at-risk / assignment alerts,
--     addressed to a specific user.
-- ============================================================================

ALTER TABLE work_orders ADD COLUMN completed_at TIMESTAMPTZ;

-- Backfill: the seeded IN_PROGRESS/NEW/ASSIGNED orders are not complete, so
-- there is nothing to backfill. Kept explicit so the intent is on the record.
UPDATE work_orders SET completed_at = NULL WHERE status NOT IN ('COMPLETED', 'CLOSED');

CREATE SEQUENCE work_order_code_seq START WITH 4 INCREMENT BY 1;

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
CREATE TABLE notifications (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id  BIGINT       NOT NULL,
    work_order_id BIGINT,
    type          VARCHAR(30)  NOT NULL,
    title         VARCHAR(200) NOT NULL,
    message       VARCHAR(1000),
    read_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id),
    CONSTRAINT ck_notifications_type
        CHECK (type IN ('SLA_BREACH', 'SLA_AT_RISK', 'WORK_ORDER_ASSIGNED',
                        'STATUS_CHANGED'))
);

CREATE INDEX idx_notifications_recipient ON notifications (recipient_id);
CREATE INDEX idx_notifications_unread    ON notifications (recipient_id, read_at);
